Repository lavary/crunz, pull requests merged in 2019-01, with the labels that each got.

#178 fix incorrect timezone in log files
  README.md
  crunz.yml
  src/Configuration/Definition.php
  src/Logger/LoggerFactory.php
  tests/Unit/Logger/FileLoggerTest.php
  tests/crunz.yml
Labels: enhancement

#185 Fix PHPUnit's test suites name
  phpunit.xml
Labels: bug

#187 Release v1.11.0
  CHANGELOG.md
  README.md
  crunz
Labels: release

#191 Release v1.11.1
  CHANGELOG.md
  README.md
  crunz
Labels: release
